name: Post welcom comment
on:
  pull_request:
    types: [opend]
permissions:
  pull-requests: write
jobs:
  build:
    name: Postwelcom comment
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_UTL --body "Welcome to the repository!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
